name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      deployType:
        description: 'Type of Deployment (Internal or External)'
        required: true
        default: 'Internal'

jobs:
  deploy:
    runs-on: [self-hosted, login]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 (Conditional)
        run: |
          if [ "${{ github.event.inputs.deployType }}" == "Internal" ]; then
            echo "Deploying Internal"
            ./deploy_from_ecr_internal.sh
          else
            echo "Deploying External"
            ./deploy_from_ecr_external.sh
          fi
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
