name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Add your EC2 public IP to GitHub Secrets
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }} # Add your private SSH key to GitHub Secrets
          envs:
            AWS_REGION: ${{ secrets.AWS_REGION }} # Add your AWS region to GitHub Secrets
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # Add your AWS Account ID to GitHub Secrets
          script: |
            cd /path/to/your/scripts
            chmod +x ./deploy_from_ecr.sh
            ./deploy_from_ecr.sh
